# Generated by Django 4.2.3 on 2023-09-29 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default=2, max_length=100, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(default=12221, max_length=100, unique=True, verbose_name='National ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default=123, max_length=100, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=2121212, max_digits=10, verbose_name='Salary'),
            preserve_default=False,
        ),
    ]
