# Generated by Django 4.2.3 on 2023-10-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee_first_name_employee_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(max_length=8, unique=True, verbose_name='National ID'),
        ),
    ]
