# Generated by Django 4.2.3 on 2023-09-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_salerecord_sale_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecord',
            old_name='sale_date',
            new_name='sale_datetime',
        ),
    ]
